config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "flats#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :flats do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[show] do
    resources :flat_reviews, only: %i[new create]
  end

  resources :users, only: :show do
    resources :user_reviews, only: %i[new create]
  end

  resources :flat_reviews, only: %i[edit update]
  resources :user_reviews, only: %i[edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  belongs_to :flat_review, optional: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user

  has_many  :bookings, dependent: :destroy

  has_many :flat_reviews, dependent: :destroy

  has_many_attached :photos

  include PgSearch::Model
  # multisearchable against: [:title, :synopsis]
  pg_search_scope :search,
  against: [ :name, :city, :zipcode, :description ],
  using: {
    tsearch: { prefix: true }
  }
  geocoded_by :full_address
  after_validation :geocode
end

app/models/flat_review.rb
class FlatReview < ApplicationRecord
  belongs_to :booking
  belongs_to :flat
  AUTHORIZED_RATINGS = (1..5)
  validates :rating, inclusion: { in: AUTHORIZED_RATINGS }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_reviews, dependent: :destroy
  has_many :flats, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_one_attached :photo
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(user)
  #   root_path
  # end
  private

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :password, :first_name, :last_name, :photo, :phone_number]  )
  devise_parameter_sanitizer.permit(:account_update, keys: [:password, :first_name, :last_name, :photo, :phone_number]  )
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show]
  def show
    @booking = Booking.find(params[:id])
    @flat = Flat.find(@booking.flat_id)
    booked_time =  @booking.end_date.to_time-@booking.start_date.to_time
    @booked_days = booked_time/(24*60*60)
    @marker = [{
      lng: @flat.longitude,
      lat: @flat.latitude,
      marker_html: render_to_string(partial: "marker")
    }]
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(params_booking)
    # @user=current_user
    @flat=Flat.find(params[:flat_id])
    @booking.flat_id=@flat.id
    @booking.user_id = current_user.id
    booked_time =  @booking.end_date.to_time-@booking.start_date.to_time
    @booked_days = booked_time/(24*60*60)
    @booking.payment_amount = @booked_days * @flat.price
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  def params_booking
    params.require(:booking).permit(:start_date, :end_date, :payment_amount, :flat_id, :user_id, :price, :mean_rating, :photos)
  end

end

app/controllers/flat_reviews_controller.rb
class FlatReviewsController < ApplicationController
  before_action :set_flat_review, only: [:edit, :update]
  def new
    @booking_id = Booking.find(params[:booking_id])
    @flat_review = FlatReview.new
  end

  def create

    @flat_review = FlatReview.new(flat_review_params)
    @booking_id = Booking.find(params[:booking_id])
    @flat_review.booking_id = @booking_id.id
    @flat_review.flat_id = @booking_id.flat_id
    if @flat_review.save!
      average_calculation

      redirect_to user_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @flat_review.update(flat_review_params)
    @flat_review.save!
    average_calculation
    redirect_to booking_path(@flat_review)
  end

  private

  def average_calculation
    @flat_review.flat_id
    count = FlatReview.where(flat_id: @flat_review.flat_id).count
    moy = (FlatReview.where(flat_id: @flat_review.flat_id).sum(:rating).to_f / count).round(1)
    current_flat = Flat.find(@flat_review.flat_id)
    current_flat.mean_rating = moy
    current_flat.save
  end

  def set_flat_review
    @flat_review = FlatReview.find(params[:id])
  end

  def flat_review_params
    params.require(:flat_review).permit(:comment, :rating)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @orderby = 'id'
    @order = 'ASC'

    if params['query'].present?
      @flats = Flat.search(params['query']).order("#{@orderby} #{@order}")
    else
      @flats = Flat.all.order("#{@orderby} #{@order}")
    end
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    # if @flat.photos.attached?
    #   @photos = @flat.photo.key
    # end

    @reviews = FlatReview.where(flat_id: @flat.id)
    @mean_rating = @flat.flat_reviews.average(:rating).to_f.round(1)
  end

  def new
    @flat = Flat.new
  end

  def edit
    @flat=Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(params_flat)
    @flat.user_id = current_user.id
    @flat.full_address = "#{@flat.street}, #{@flat.zipcode} #{@flat.city}"
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def update
    @flat.update!(params_flat)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private
  def set_flat
    @flat = Flat.find(params[:id])
  end

  def params_flat
    params.require(:flat).permit(:name, :city, :zipcode, :street, :full_address, :description , :price, :mean_rating, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  before_action :set_user_review, only: [:edit, :update]
  def new
    @user_id = User.find(params[:user_id])
    @user_review = UserReview.new
  end

  def create
    @user_id = User.find(params[:user_id])
    @user_review = UserReview.new(user_review_params)
    @user_review.user_id = @user_id.id
    if @user_review.save!
      redirect_to user_path(@user_id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @user_review.update(user_review_params)
    @user_review.save!
    redirect_to user_path(@user_review)
  end

  private

  def set_user_review
    @user_review = UserReview.find(params[:id])
  end

  def user_review_params
    params.require(:user_review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @bookings = @user.bookings
    @flats = @user.flats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_marker.html.erb
<%= image_tag 'pin.png', width: 60, height: 60 %>

app/views/bookings/new.html.erb
<div class="container">
  <div id="booking-form" class="inner-container shadow p-3">
    <div class="form-container mb-5 text-center", data-controller="form">
      <h1 id="another-gradient">Your booking</h1>
        <%= simple_form_for @booking, url: flat_bookings_path do |f| %>
        <div class="form-inputs">
          <div class="row justify-content-center w-100">
            <div class="col-5">
            <%#= f.input :start_date, as: :string, :input_html => { :class => 'date', data: {controller: "booking-date-start"} } %>
            <%#= f.input :end_date, as: :string, :input_html => { :class => 'date', data: {controller: "booking-date-end"} } %>
            <%= f.input :start_date, as: :string, :label => "Dates", input_html: { data: { controller: "booking-date-both", target: "booking-date-both.entryDate" } } %>
            </div>
            <%= f.input :end_date, as: :string, as: :hidden %>
            </div>
            <%# <%= f.input :payment_amount %>
            <%# <%= f.input :flat_id %>
            <%# <%= f.input :user_id %>
            <%# <%= f.input :flat_review_id %>
            <%= f.button :submit, class: "btn btn-flat"%>
            </div>
          <% end %>
          </div>
      <div class="d-flex justify-content-between border-top pt-2 mb-1">
        <%= link_to "Back", :back, class: "btn btn-flat align-self-end" %>
      </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="inner-container">
  <div class="text-center congrats" target="_blank">
    <h1>🎉 Congrats <%= current_user.first_name %> 🎉</h1>
    <h3>you booked <%= @flat.name %> !</h3>
  </div>
    <div class="d-block carousel-img">
      <%= render partial: 'components/carousel', locals: { photos: @flat.photos } %>
    </div>
  <div class="booking-details">
    <div class="description-booking">
      <p>Your stay will be from <b><%= @booking.start_date.strftime('%A %d %B %Y') %></b></p>
      <p>to <b><%= @booking.end_date.strftime('%A %d %B %Y') %></b>.</p>
      <p>So you will have <%= @booked_days.round %> days to enjoy !</p>
      <div class="bill">
        <p>Your bill is : </p>
        <p><%= @booked_days.round %> days x <%= @flat.price.round %> €/per night</p>
        <p> = <%= @booking.payment_amount.round %>€</p>
      </div>
    </div>
    <div id="mapping"
      data-controller="mapping"
      data-mapping-markers-value="<%= @marker.to_json %>"
      data-mapping-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <%= link_to "Back to list", flats_path, class: 'btn btn-flat' %>
  </div>
</div>

app/views/flat_reviews/_flat_reviews_form.html.erb
<div data-controller="flat-review-stars">

<%= simple_form_for([@booking_id, @flat_review]) do |f| %>
  <div class="form-inputs">
    <div class="row justify-content-around w-50">
      <%= f.input :comment, :input_html => {:style=> 'height: 96px'}  %>
    </div>
    <input type="hidden" name="flat_review[rating]" id="flat_review_rating" data-flat-review-stars-target="rating">
    <div class="my-3 mx-3">
      <% FlatReview::AUTHORIZED_RATINGS.each do |index| %>
        <i
          class="review-rating far fa-star"
          data-id="<%= index %>"
          data-flat-review-stars-target="star"
          <%# data-target="flat-review-stars.star" %>
          data-action="click->flat-review-stars#selectRating mouseover->flat-review-stars#hoverRating">
        </i>
      <% end %>
      <!-- Gestion du survol de la souris en dehors des étoiles -->
      <div id="review-star-ratings" data-action="mouseout->flat-review-stars#resetStars"></div>
    </div>

    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/flat_reviews/edit.html.erb
<div class="container">
  <div class="inner-container shadow p-3">
    <div class="form-container mb-5", data-controller="form">
      <h1>Change your review</h1>
      <%= render "flat_reviews_form", partial: @flat_review %>
    </div>
  </div>
</div>

app/views/flat_reviews/new.html.erb
<div class="container">
  <div class="inner-container shadow p-3">
    <div class="form-container mb-5", data-controller="form">
      <h1>Send your review</h1>
      <%= render "flat_reviews_form", partial: @flat_review %>
    </div>
    <div class="d-flex justify-content-between border-top mb-1">
        <%= link_to "Back", :back, class: "btn btn-flat align-self-end" %>
    </div>
  </div>
</div>

app/views/flats/_marker.html.erb
<%= image_tag 'pin.png', width: 40, height: 40 %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="inner-container shadow p-3">
    <div class="form-container mb-5", data-controller="form">
      <h2>Edit your flat : <%= @flat.name %></h2>
      <%= simple_form_for @flat do |f| %>
      <div class="form-inputs">
          <div class="row justify-content-around w-50">
            <%= f.input :name%>
          </div>
          <div class="row justify-content-around w-75">
          <%= f.input :description, :input_html => {:style=> 'height: 96px'} %>
          </div>
          <div class="row justify-content-around w-75">
            <%= f.input :street, label: "Number and street of your appartment" %>
          </div>

          <div class="row justify-content-around w-75">
            <div class="col-5">
            <%= f.input :zipcode %>
            </div>
            <div class="col-5">
            <%= f.input :city %>
            </div>
          </div>

          <div class="row justify-content-around w-75">
            <div class="col-5">
            <%= f.input :price %>
            </div>
            <div class="col-5">
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            </div>
          </div>
            <%= f.button :submit, class: "btn btn-flat"%>
      </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-between border-top mb-1">
        <%= link_to "Back", :back, class: "btn btn-flat align-self-end" %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<%= render "components/banner_search" %>
  <div class="row g-0 d-flex">
    <div class="cards col-8">
      <% @flats.each do |flat| %>
      <%= render "/components/card_flat_vertical", flat: flat %>
      <% end %>
    </div>
    <div class="col-4">
      <div id="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

app/views/flats/new.html.erb
<div class="container">
  <div class="inner-container shadow p-3">
    <div class="form-container mb-5", data-controller="form">
      <h2>Create your new flat</h2>
      <%= simple_form_for @flat do |f| %>
      <div class="form-inputs">
          <div class="row justify-content-around w-75">
            <%= f.input :name%>
          </div>
          <div class="row justify-content-around w-75">
          <%= f.input :description, :input_html => {:style=> 'height: 96px'} %>
          </div>
          <div class="row justify-content-around w-75">
            <%= f.input :street, label: "Number and street of your appartment" %>
          </div>

          <div class="row justify-content-around w-75">
            <div class="col-5">
            <%= f.input :zipcode %>
            </div>
            <div class="col-5">
            <%= f.input :city %>
            </div>
          </div>

          <div class="row justify-content-around w-75">
            <div class="col-5">
            <%= f.input :price %>
            </div>
            <div class="col-5">
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            </div>
          </div>
            <%= f.button :submit, class: "btn btn-flat"%>
      </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-between border-top mb-1">
        <%= link_to "Back", :back, class: "btn btn-flat align-self-end" %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="inner-container shadow p-3">
  <div class="row bg-white p-3">
    <div class="col">
      <h2><%= @flat.name %></h2>
      <div class="flat-img">
        <%= render partial: 'components/carousel', locals: { photos: @flat.photos } %>
      </div>
    </div>
    <div class="col description-flat p-5">
      <p><b>Address : </b><%= @flat.full_address %></p>
      <p><b>Description : </b><%= @flat.description %></p>
      <% if @mean_rating.round == 1 %>
        <p><b>Rating : </b><i class="fa-solid fa-star"></i></p>
        <% elsif @mean_rating.round == 2 %>
        <p><b>Rating : </b><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
        <% elsif @mean_rating.round == 3 %>
        <p><b>Rating : </b><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
        <% elsif @mean_rating.round == 4 %>
        <p><b>Rating : </b><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
        <% elsif @mean_rating.round == 5 %>
        <p><b>Rating : </b><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
      <% end %>
      <p><b>Price : </b><%= @flat.price %> €</p>
      <%= link_to "Reserver",  new_flat_booking_path(@flat), class: 'btn btn-flat' %>
    </div>
  </div>
<div >
<div class="row bg-white p-3 mt-4">
  <h3>Reviews :</h3>
  <div class="d-flex flex-wrap justify-content-around">
    <% if @reviews %>
      <% @reviews.each do |review| %>
        <%= render partial: 'components/card_flat_comment', locals: { review: review } %>
      <% end%>
    <% end %>
  </div>
</div>
  <div class="d-flex justify-content-between border-top pt-2 mb-1">
        <%= link_to "Back", flats_path, class: "btn btn-flat align-self-end" %>
    </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirCnc</title>
    <%= favicon_link_tag 'aircnc_logo.png' %>
    <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
    <%= render 'components/navbar' %>
  </head>

  <body>
    <%# if current_user %>
      <%# if  current_user.first_name==nil && current_user.last_name==nil && current_user.phone_number==nil%>
      <%# <p class="notice"><%= "You should enter your informations" %>
      <%# end %>
    <%# else %>
      <%# <p class="notice"><%= "Sign to have all the app features" %>
    <%# end %>
    <%= yield %>
  </body>
  <% if params['controller'] != "devise/sessions" %>
    <% if params['controller'] != "bookings" %>
      <%= render 'components/footer' %>
    <% end %>
  <% end %>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
<%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete} %>
<% else %>
<%= link_to "Sign In", new_user_session_path %>
<%= link_to  "Sign Up", new_user_registration_path %>
<% end %>

app/views/user_reviews/_user_reviews_form.html.erb
<%= simple_form_for ([@user_id, @user_review]) do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: Review::AUTHORIZED_RATINGS, include_blank: false %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/user_reviews/edit.html.erb
<h1>UserReviews#edit</h1>
<p>Find me in app/views/user_reviews/edit.html.erb</p>
<%= render "user_reviews_form", partial: @user_review %>

app/views/user_reviews/new.html.erb
<h1>UserReviews#new</h1>
<p>Find me in app/views/user_reviews/new.html.erb</p>
<%= render "user_reviews_form", partial: @user_review %>

app/views/users/show.html.erb
<div class="container">
  <div class="inner-container shadow">
    <div class="d-flex justify-content-between mx-5 mt-3">
      <div class="col-8" id="user-info">
        <h1 id='another-gradient' class='animation-top'>Your Dashboard</h1>
        <%= render '/components/description_user' %>
      </div>
      <div class="col-4 update-position">
        <%= link_to "Update profile", edit_user_registration_path, class: "btn btn-flat align-self-baseline" %>
      </div>
    </div>

    <div class="d-flex justify-content-around m-5" id="bookings-and-flats">
      <div class="col-5 animation-left" id="bookings">
        <h2>My bookings</h2>
        <div class="mt-3">
          <%= render '/components/card_flat_horizontal_review', partial: @bookings %>
        </div>
      </div>

      <div class="col-5 animation-right" id="flats">
        <div class="d-flex justify-content-between">
          <h2 style="margin-bottom: 8px;">My flats</h2>
          <%= link_to 'Add a flat', new_flat_path, class: "btn btn-flat" %>
        </div>
        <div class="mt-3">
          <%# si (il a un booking ET que j'ai laissé une review) OU (il n'a pas de booking) %>
          <%= render '/components/card_flat_horizontal', partial: @flats %>
          <%# Sinon on affiche avec un bouton review %>
          <%# <%= link_to 'add a Review to the tenant', new_user_user_review_path(flat.user_id) %>
        </div>
      </div>
    </div>
  </div>
</div>